<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;

/**
 * One-time migration of the original hardcoded service copy (formerly in
 * FrontendController::services()) into the Voyager-managed `services` table.
 * Safe to re-run — upserts on slug rather than duplicating rows.
 */
class ServicesTableSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->data() as $order => $row) {
            $row['order'] = $order + 1;
            Service::updateOrCreate(['slug' => $row['slug']], $row);
        }
    }

    private function data(): array
    {
        return [
            [
                'slug' => 'ghostwriting',
                'nav_title' => 'Ghostwriting',
                'summary' => 'Have a story but need the words? Our writers shape your ideas into a polished manuscript that sounds like you.',
                'icon' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z"></path></svg>',
                'title' => 'Ghostwriting That Sounds Like ',
                'title_accent' => 'You',
                'meta_description' => 'Professional ghostwriting that captures your voice — memoir, business books and fiction, written to a schedule you can plan around.',
                'lede' => "Have a story in your head but no time to write it down? Our professional ghostwriters work in your voice, follow your outline, and deliver chapters on a schedule you can keep up with.",
                'included_heading' => 'From Outline to Finished Manuscript',
                'included_text' => "Whether you have a full outline, a stack of voice notes, or just a story you've been meaning to tell, our ghostwriters turn it into a publish-ready manuscript — memoir, business book, or fiction — without losing your voice along the way.",
                'included_list' => implode("\n", [
                    'In-depth author interviews to capture your voice and story',
                    'Chapter-by-chapter drafts on an agreed delivery schedule',
                    'Full-length manuscripts up to 30,000+ words',
                    'Unlimited revisions on select packages',
                    'A dedicated project manager throughout',
                    '100% ownership and confidentiality — your name, your rights',
                ]),
                'image' => 'assets/images/hero-desk.jpg',
                'image_alt' => "An author's writing desk with manuscript, fountain pen and hardcover books",
                'process_heading' => 'Our Ghostwriting Process',
                'steps' => implode("\n", [
                    'Discovery Call|We talk through your story, goals and timeline, then match you with a ghostwriter suited to your genre.',
                    "Outline & Voice Sample|Before a single chapter is drafted, we build a chapter outline and a short sample so you can confirm the voice feels right.",
                    "Drafting|Chapters arrive on a set schedule with regular check-ins, so you're never waiting in the dark for progress.",
                    'Review & Revision|You review the full manuscript and request changes — we refine until it reads exactly as you intended.',
                    'Handoff|You receive the final manuscript, fully yours, ready for editing and design.',
                ]),
                'testimonial_title' => 'Exceptional Editing & Publishing',
                'testimonial_quote' => 'The editors refined my story while keeping my voice intact. The whole publishing process was smooth and transparent.',
                'testimonial_initials' => 'PG',
                'testimonial_name' => 'Phillip G.D. Jones',
                'testimonial_date' => 'Mar 12, 2024',
                'cta_eyebrow' => 'Ready to Start Writing?',
                'cta_heading' => "Let's Get Your Story on the Page",
                'cta_text' => "Book a free consultation and we'll match you with the right ghostwriter for your genre.",
                'faq_question_1' => 'Will the book sound like it was written by me?',
                'faq_answer_1' => "Yes — that's the whole point. Every project starts with in-depth interviews so your ghostwriter can match your voice, tone and vocabulary, not their own.",
                'faq_question_2' => 'Do I own the finished manuscript?',
                'faq_answer_2' => "Completely. You retain 100% ownership and rights, and your ghostwriter's involvement stays confidential unless you choose to credit them.",
                'faq_question_3' => 'How long does ghostwriting a book take?',
                'faq_answer_3' => 'Most full-length manuscripts take 3–6 months depending on length and revision rounds, with chapters delivered on an agreed schedule throughout.',
            ],
            [
                'slug' => 'editing-proofreading',
                'nav_title' => 'Editing & Proofreading',
                'summary' => 'Line editing, structural feedback and meticulous proofreading so your book is error-free and reader-ready.',
                'icon' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M21 5H3"></path><path d="M17 12H3"></path><path d="M21 19H3"></path><path d="m17 8 4 4-4 4"></path></svg>',
                'title' => 'Editing That Makes Agents ',
                'title_accent' => 'Say Yes',
                'meta_description' => "Developmental editing, line editing and proofreading that gets your manuscript to a professional, reader-ready standard.",
                'lede' => 'Even strong manuscripts get rejected over weak editing. Our editors handle developmental editing, line editing, copyediting and proofreading — line by line, chapter by chapter.',
                'included_heading' => 'Four Layers of Editorial Polish',
                'included_text' => 'We match your manuscript with editors who work in your genre, then move through structural, line and copy edits before a final proofread — so nothing gets missed.',
                'included_list' => implode("\n", [
                    'Developmental editing for structure, pacing and plot',
                    'Line editing for voice, clarity and flow',
                    'Copyediting for grammar, consistency and style',
                    'Final proofread before formatting and print',
                    'Editor notes and a marked-up manuscript, not just clean copy',
                    'A dedicated editor who stays with your book start to finish',
                ]),
                'image' => 'assets/images/book-nonfiction.jpg',
                'image_alt' => 'A finished hardcover book ready for print',
                'process_heading' => 'Our Editing Process',
                'steps' => implode("\n", [
                    'Manuscript Assessment|We read your full manuscript and flag the structural issues before touching a single sentence.',
                    'Developmental Edit|We address plot, pacing, character arcs or argument structure — the big-picture fixes that matter most.',
                    'Line & Copy Edit|Sentence-level editing for voice and clarity, followed by a grammar and consistency pass.',
                    'Author Review|You review every suggested change and approve or adjust before we move to final proofreading.',
                    'Final Proofread|One last pass immediately before formatting, catching anything introduced during revisions.',
                ]),
                'testimonial_title' => 'Great Support for First-Time Authors',
                'testimonial_quote' => 'The editorial team was patient, detailed and professional. I felt supported throughout the entire publishing journey.',
                'testimonial_initials' => 'MG',
                'testimonial_name' => 'Maria Garcia',
                'testimonial_date' => 'Oct 3, 2024',
                'cta_eyebrow' => 'Ready for a Second Pair of Eyes?',
                'cta_heading' => "Let's Polish Your Manuscript",
                'cta_text' => "Send us your draft and we'll recommend the right level of edit for where it stands today.",
                'faq_question_1' => "What's the difference between developmental editing and copyediting?",
                'faq_answer_1' => 'Developmental editing addresses big-picture issues like structure, pacing and plot. Copyediting focuses on grammar, consistency and style once the structure is already solid.',
                'faq_question_2' => 'Do I need every level of edit, or can I choose just one?',
                'faq_answer_2' => "You can book any single layer or the full package — we'll recommend where your manuscript actually needs the most work after an initial assessment.",
                'faq_question_3' => '',
                'faq_answer_3' => '',
            ],
            [
                'slug' => 'cover-design',
                'nav_title' => 'Cover Design & Illustration',
                'summary' => "Covers and interior artwork that capture your story at a glance — from children's books to literary fiction.",
                'icon' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><circle cx="13.5" cy="6.5" r=".5"></circle><circle cx="17.5" cy="10.5" r=".5"></circle><circle cx="8.5" cy="7.5" r=".5"></circle><circle cx="6.5" cy="12.5" r=".5"></circle><path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z"></path></svg>',
                'title' => 'Covers Readers ',
                'title_accent' => 'Judge (and Buy)',
                'meta_description' => "Covers and interior artwork that capture your story at a glance — from children's picture books to literary fiction.",
                'lede' => "Covers and interior artwork that capture your story at a glance — from children's picture books to literary fiction, designed to stop the scroll on a bookstore shelf or an Amazon thumbnail.",
                'included_heading' => 'Design That Matches Your Genre',
                'included_text' => "A thriller cover and a picture book cover need completely different design instincts. We match your project with an illustrator or designer who works in your genre, then iterate until it's right.",
                'included_list' => implode("\n", [
                    'Custom front cover concepts, not template mockups',
                    'Full wraparound design for print (front, spine, back)',
                    'Interior formatting for print and e-book',
                    "Full-colour illustration for children's and picture books",
                    'Multiple concept rounds with revisions included',
                    'Print-ready files at trim size and bleed for any printer',
                ]),
                'image' => 'assets/images/book-children.jpg',
                'image_alt' => "Illustrated children's book cover",
                'process_heading' => 'Our Design Process',
                'steps' => implode("\n", [
                    "Creative Brief|We talk genre, comp titles and mood — the covers you love and the ones you don't.",
                    'Concept Round|Your designer presents two to three distinct cover directions to react to.',
                    "Refinement|We narrow to one direction and refine typography, imagery and colour until it's launch-ready.",
                    'Interior Formatting|Once the cover is locked, we format the interior for print and e-book to match.',
                    'Final Files|You receive print-ready and digital files sized correctly for every platform you publish on.',
                ]),
                'testimonial_title' => "Amazing Children's Book Illustration",
                'testimonial_quote' => 'The characters were vibrant and perfectly matched the tone of my story. Kids absolutely love the visuals.',
                'testimonial_initials' => 'ST',
                'testimonial_name' => 'Sarah Thompson',
                'testimonial_date' => 'Jun 15, 2024',
                'cta_eyebrow' => 'Ready to See Your Cover?',
                'cta_heading' => "Let's Design Something Readers Notice",
                'cta_text' => "Tell us about your book and genre — we'll match you with the right designer.",
                'faq_question_1' => 'How many cover concepts will I see?',
                'faq_answer_1' => 'Your designer presents two to three distinct directions in the first concept round, then we refine your chosen direction through additional revision rounds.',
                'faq_question_2' => 'Can you design both the print and e-book versions?',
                'faq_answer_2' => 'Yes — we deliver a full wraparound print cover (front, spine, back) alongside a separate e-book-optimised front cover, sized correctly for every platform.',
            ],
            [
                'slug' => 'publishing-distribution',
                'nav_title' => 'Publishing & Distribution',
                'summary' => 'Formatting and release on Amazon, IngramSpark and other major platforms — print, e-book and beyond.',
                'icon' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"></path><path d="M2 12h20"></path></svg>',
                'title' => 'Published Everywhere ',
                'title_accent' => 'Readers Shop',
                'meta_description' => 'Formatting and release on Amazon, IngramSpark and other major platforms — print, e-book and beyond, with your ISBN assigned to you.',
                'lede' => 'Print, e-book, hardcover, paperback. We format your manuscript to industry standards, assign your ISBN, set up distribution, and put your book on every retailer that matters. You stay in control — we do the heavy lifting.',
                'included_heading' => 'Wherever Readers Buy Books',
                'included_text' => "We handle the technical side of getting a book to market — formatting, metadata, ISBN registration and retailer setup — so you go from finished file to available-for-purchase without the guesswork.",
                'included_list' => implode("\n", [
                    'Print and e-book formatting to retailer specifications',
                    'ISBN assignment, registered in your name',
                    'Amazon KDP, IngramSpark and Barnes & Noble setup',
                    'Global e-book distribution (Apple Books, Kobo, Google Play)',
                    'Metadata, categories and keyword optimisation',
                    'Author copies and print-on-demand set up for ongoing orders',
                ]),
                'image' => 'assets/images/book-fiction.jpg',
                'image_alt' => 'A published novel cover',
                'process_heading' => 'Our Publishing Process',
                'steps' => implode("\n", [
                    'Format Selection|We confirm which formats you want live — paperback, hardcover, e-book, or all three.',
                    "Technical Formatting|Your final manuscript is formatted to each retailer's exact specifications for trim size and layout.",
                    'ISBN & Metadata|We register your ISBN and write retailer-optimised titles, descriptions and keywords.',
                    "Platform Setup|Your book goes live on Amazon, IngramSpark and the retailers you've chosen.",
                    'Launch Check|We verify every listing looks right and order a proof copy before announcing your release.',
                ]),
                'testimonial_title' => 'Professional Audiobook Production',
                'testimonial_quote' => 'Narration, editing and production were handled perfectly. The audiobook opened a completely new audience for my book.',
                'testimonial_initials' => 'RL',
                'testimonial_name' => 'Robert Lee',
                'testimonial_date' => 'Oct 20, 2024',
                'cta_eyebrow' => 'Ready to Go Live?',
                'cta_heading' => "Let's Get Your Book on Shelves",
                'cta_text' => "Tell us which formats and platforms matter most to you — we'll map out the fastest path to launch.",
                'faq_question_1' => 'Who owns the ISBN once the book is published?',
                'faq_answer_1' => 'You do — every ISBN we register is assigned in your name, not ours, so you retain full control of your publishing record.',
                'faq_question_2' => 'Which retailers can you distribute to?',
                'faq_answer_2' => 'Amazon KDP, IngramSpark and Barnes & Noble for print, plus global e-book distribution through Apple Books, Kobo and Google Play.',
                'faq_question_3' => 'How long does it take to go from finished file to available for purchase?',
                'faq_answer_3' => 'Typically 2–4 weeks once formatting is finalised, depending on how many platforms and formats you launch on simultaneously.',
            ],
            [
                'slug' => 'book-marketing',
                'nav_title' => 'Book Marketing',
                'summary' => 'Bespoke launch campaigns, social promotion and PR support that put your book in front of the right readers.',
                'icon' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="m3 11 18-5v12L3 14v-3z"></path><path d="M11.6 16.8a3 3 0 1 1-5.8-1.6"></path></svg>',
                'title' => 'A Launch Plan, ',
                'title_accent' => 'Not Just a Launch Day',
                'meta_description' => 'Launch campaigns, social promotion and PR support that put your book in front of the right readers.',
                'lede' => 'Bespoke launch campaigns, social promotion and PR support that put your book in front of the right readers — before, during and after release day.',
                'included_heading' => 'Marketing Built Around Your Book',
                'included_text' => "A great book still needs readers to find it. We build a launch plan around your genre and audience, then run it — so you spend your time writing the next one, not chasing algorithms.",
                'included_list' => implode("\n", [
                    'Amazon listing optimisation (title, keywords, categories, A+ content)',
                    'Author website and landing page',
                    'Social media launch kit and content calendar',
                    'Press release and media/blogger outreach',
                    'Advance reader copy (ARC) distribution for early reviews',
                    'Email launch sequence for your subscriber list',
                ]),
                'image' => 'assets/images/book-horror.jpg',
                'image_alt' => 'A book on a shelf ready for launch',
                'process_heading' => 'Our Marketing Process',
                'steps' => implode("\n", [
                    'Audience & Positioning|We identify who your ideal reader is and how your book should be positioned against comp titles.',
                    'Launch Kit Build|Listing copy, social assets, press materials and email sequences are drafted ahead of release.',
                    'Pre-Launch Buzz|ARC distribution and outreach start building early reviews and momentum before release day.',
                    'Launch Week|Coordinated social, email and PR push around your release date to maximise first-week sales and rankings.',
                    "Post-Launch Momentum|We monitor performance and keep the campaign running so your book keeps finding readers after week one.",
                ]),
                'testimonial_title' => 'Powerful Book Marketing Strategy',
                'testimonial_quote' => "Their campaigns improved my book's visibility and boosted sales. I was impressed by their knowledge of the market.",
                'testimonial_initials' => 'MR',
                'testimonial_name' => 'Michael Rodriguez',
                'testimonial_date' => 'Jan 16, 2024',
                'cta_eyebrow' => 'Ready to Reach Readers?',
                'cta_heading' => "Let's Plan Your Launch",
                'cta_text' => "Tell us your release timeline and we'll build a campaign around it.",
                'faq_question_1' => 'When should I start marketing my book?',
                'faq_answer_1' => 'Ideally 90 days before release — early reviews, an author website and a growing email list all compound in the weeks before launch day.',
                'faq_question_2' => 'Do you handle paid ads as well as organic promotion?',
                'faq_answer_2' => "Our core package covers listing optimisation, social, PR and email — paid ad campaigns can be added on top once we see how your organic launch performs.",
            ],
            [
                'slug' => 'audiobook-production',
                'nav_title' => 'Audiobook Production',
                'summary' => 'Professional narration, editing and mastering that brings your book to listeners everywhere.',
                'icon' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="M2 10v4"></path><path d="M6 6v12"></path><path d="M10 3v18"></path><path d="M14 8v9"></path><path d="M18 5v14"></path><path d="M22 10v4"></path></svg>',
                'title' => 'Give Your Book ',
                'title_accent' => 'a Voice',
                'meta_description' => 'Professional narration, editing and mastering that brings your book to listeners on Audible, Apple Books and Spotify.',
                'lede' => 'Professional narration, editing and mastering that brings your book to listeners on Audible, Apple Books and Spotify — a growing audience many authors never reach.',
                'included_heading' => 'Studio-Quality Production',
                'included_text' => "We handle casting, direction, recording and post-production, so your audiobook meets the technical standards Audible and Apple Books require — without you needing a home studio.",
                'included_list' => implode("\n", [
                    'Narrator casting and voice sample selection',
                    'Professional studio recording and direction',
                    'Editing, levelling and noise reduction',
                    'ACX/Audible technical compliance mastering',
                    'Distribution to Audible, Apple Books and Spotify',
                    'Optional multi-voice production for fiction and dialogue-heavy books',
                ]),
                'image' => 'assets/images/book-audio.jpg',
                'image_alt' => 'Audiobook cover art',
                'process_heading' => 'Our Audiobook Process',
                'steps' => implode("\n", [
                    'Narrator Casting|We shortlist narrators suited to your genre and send voice samples for you to choose from.',
                    'Recording|Your narrator records in a professional studio, directed to match the tone of your book.',
                    'Editing & Mastering|Audio is edited for pacing and cleaned up to meet platform loudness and noise-floor requirements.',
                    'Quality Review|You review chapter samples and request any re-reads before final approval.',
                    'Distribution|We upload and configure your audiobook across Audible, Apple Books and Spotify.',
                ]),
                'testimonial_title' => 'Professional Audiobook Production',
                'testimonial_quote' => 'Narration, editing and production were handled perfectly. The audiobook opened a completely new audience for my book.',
                'testimonial_initials' => 'RL',
                'testimonial_name' => 'Robert Lee',
                'testimonial_date' => 'Oct 20, 2024',
                'cta_eyebrow' => 'Ready for Listeners?',
                'cta_heading' => "Let's Produce Your Audiobook",
                'cta_text' => "Tell us about your book and we'll recommend the right narrator and production path.",
                'faq_question_1' => 'Do I get to choose the narrator?',
                'faq_answer_1' => "Yes — we shortlist narrators suited to your genre and send you voice samples so you can pick the one that fits your book before recording begins.",
                'faq_question_2' => 'Will the audiobook meet Audible/ACX requirements?',
                'faq_answer_2' => 'Every production is edited, levelled and mastered to ACX/Audible technical compliance standards before distribution.',
                'faq_question_3' => 'Can you produce a multi-voice audiobook for dialogue-heavy fiction?',
                'faq_answer_3' => "Yes, multi-voice production is available as an add-on — particularly popular for fiction with distinct character voices.",
            ],
        ];
    }
}
